### ISSUE TITLE
[BUG] Mac Installation 

### ISSUE THREAD

**Issue by cbalaf** [dessa-oss/atlas#116]
**Platform & setup**
Mac OS 10.13.6
Docker Desktop 2.2.0.3 running with Docker Engine 19.03.5

**Describe the bug**
Installation fails with `docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://us.gcr.io/v2/: Service Unavailable")`

**To Reproduce**
I just ran `python atlas_installer.py` on a directory with only the `atlas_installer.py` file and a clean conda environment

**Additional context / Stacktrace**
```
Loading image: us.gcr.io/dessa-atlas/foundations/archive_server:latest
Traceback (most recent call last):
  File "/Users/kbalafas/opt/anaconda3/envs/atlas/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/Users/kbalafas/opt/anaconda3/envs/atlas/lib/python3.8/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/images/create?tag=latest&fromImage=us.gcr.io%2Fdessa-atlas%2Ffoundations%2Farchive_server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "atlas_installer.py", line 691, in <module>
    load_docker_images(args.use_specified_version)
  File "atlas_installer.py", line 112, in load_docker_images
    image_loader.pull_image(image['name'], tag=image['tag'] if use_specified_version else "latest")
  File "atlas_installer.py", line 70, in pull_image
    image = self._client.images.pull(repo, tag)
  File "/Users/kbalafas/opt/anaconda3/envs/atlas/lib/python3.8/site-packages/docker/models/images.py", line 443, in pull
    pull_log = self.client.api.pull(
  File "/Users/kbalafas/opt/anaconda3/envs/atlas/lib/python3.8/site-packages/docker/api/image.py", line 414, in pull
    self._raise_for_status(response)
  File "/Users/kbalafas/opt/anaconda3/envs/atlas/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/kbalafas/opt/anaconda3/envs/atlas/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://us.gcr.io/v2/: Service Unavailable")
```

**Comment by mohammedri** [comment]
Hey @cbalaf did you download the latest version from https://github.com/dessa-oss/atlas/releases/tag/0.1.1 ?

**Comment by mohammedri** [comment]
@cbalaf could you try running the installer using a Python 3.7 Environment?

**Comment by cbalaf** [comment]
Downloaded the latest versions of both `atlas.tgz` and `atlas_installer.py` and ran them in a python 3.7 environment. Same error

**Comment by mohammedri** [comment]
Tried this on: 
* MacOS version: 10.15.3 Catalina
* Docker version: 19.03.5, build 633a0ea
* Python version: 3.7.7
* Release: https://github.com/dessa-oss/atlas/releases/download/0.1.1/atlas_installer.py

& 

* Ubuntu VERSION="18.04.3 LTS (Bionic Beaver)"
* Docker version 19.03.5, build 633a0ea838
* Python version: 3.6 
* Release: https://github.com/dessa-oss/atlas/releases/download/0.1.1/atlas_installer.py

& 

* Ubuntu VERSION="18.04.3 LTS (Bionic Beaver)"
* Docker version 19.03.5, build 633a0ea838
* Python version: 3.7.7 
* Release: https://github.com/dessa-oss/atlas/releases/download/0.1.1/atlas_installer.py

Without any failures in installation.

Unable to replicate this @cbalaf , could you try again? You should only need the `atlas_installer.py`.

**Comment by mohammedri** [comment]
Closing as unable to replicate. @cbalaf please re-open if the issue persists.
