### ISSUE TITLE
Installing for local machine errors 

### ISSUE THREAD

**Issue by CaffineAddic** [dessa-oss/atlas#192]
**Platform & setup**
Fedora Linux 37 (Workstation Edition)
Kernel   6.0.15-300.fc37.x86_64 
Docker version 20.10.21, build baeda1f

**Describe the bug**
Unable to install Atlas-server 

**To Reproduce**
1. Created a conda virtual environment on python 3.7
2. Downloaded the latest atlas_installer.py
3. Running python atlas_installer.py after activating the virtual env

Unpacking installation package atlas.tgz
Installing installer requirements PyYAML==5.1.2, requests==2.19.1
Requirement already satisfied: PyYAML==5.1.2 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (5.1.2)
Requirement already satisfied: requests==2.19.1 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (2.19.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from requests==2.19.1) (2022.12.7)
Requirement already satisfied: idna<2.8,>=2.5 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from requests==2.19.1) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from requests==2.19.1) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from requests==2.19.1) (1.23)
Installing installer requirements docker==4.0.2
Requirement already satisfied: docker==4.0.2 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (4.0.2)
Requirement already satisfied: six>=1.4.0 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from docker==4.0.2) (1.16.0)
Requirement already satisfied: websocket-client>=0.32.0 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from docker==4.0.2) (1.4.2)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from docker==4.0.2) (2.19.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.0.2) (2022.12.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.0.2) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.0.2) (2.7)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/saumya/.conda/envs/atlas/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.0.2) (1.23)
atlas_installer.py:108: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  images = yaml.load(f)
Loading image: us.gcr.io/dessa-atlas/foundations/archive_server:latest
Traceback (most recent call last):
  File "/home/saumya/.conda/envs/atlas/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/saumya/.conda/envs/atlas/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/images/create?tag=latest&fromImage=us.gcr.io%2Fdessa-atlas%2Ffoundations%2Farchive_server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "atlas_installer.py", line 691, in <module>
    load_docker_images(args.use_specified_version)
  File "atlas_installer.py", line 112, in load_docker_images
    image_loader.pull_image(image['name'], tag=image['tag'] if use_specified_version else "latest")
  File "atlas_installer.py", line 70, in pull_image
    image = self._client.images.pull(repo, tag)
  File "/home/saumya/.conda/envs/atlas/lib/python3.7/site-packages/docker/models/images.py", line 444, in pull
    repository, tag=tag, stream=True, **kwargs
  File "/home/saumya/.conda/envs/atlas/lib/python3.7/site-packages/docker/api/image.py", line 414, in pull
    self._raise_for_status(response)
  File "/home/saumya/.conda/envs/atlas/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/saumya/.conda/envs/atlas/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication")

**Comment by CaffineAddic** [comment]
Anyone help???

**Comment by tyllrb** [comment]
getting this too, install script gets the docker images from a google cloud registry which now seems to be behind an authentication wall...I have a feeling this is a dead repo so this probably won't get resolved :(

**Comment by CaffineAddic** [comment]
Ya sadly, I went upto use ANTs (Advance Normalization tools) package for segmentation.
